### PR TITLE
Add -S option to allow user to specify a minimum number of sectors. Update -x and -X to use the new track and side specifying format.

### PR DESCRIPTION
**Pull request by qbarnes**

### CODE REVIEW

**Review by TimothyPMann — COMMENTED** [review]
separated by a commas. -> separated by commas.

**Review by TimothyPMann — APPROVED** [review]
more or less sectors are encountered -> more or fewer sectors are encountered

**Comment by TimothyPMann** [comment]
I guess I should have selected "request changes" instead of "approve" since I had two minor grammar nits in the man page to point out.

It looks good otherwise, although I didn't really review the changes to track/side parsing. I gather you unit-tested them well as you described in email.

**Comment by qbarnes** [comment]
Don't worry about what status GitHub may get set to.  I do as much as I can via good old `git` anyway.

Thank you for catching the grammar goofs.

When I first saw your comment, I was kicking myself because I had planned to run the man page through a spell checker, but forgot.  Then I realized that it wouldn't have mattered!  The spelling of my grammar mistakes were just annoyingly fine.  :)  However, I did run the 4 man pages through spellcheck, and the pass turned up some typos in `cw2dmk.man` that I corrected along with the noted goofs.

**Pull request merged**
