### PR TITLE
Update man page to reflect max tracks change to 88

### PR DESCRIPTION
**Pull request by TimothyPMann**

### CODE REVIEW

**Review by qbarnes — APPROVED** [review]
Are we going to eventually need to make an equivalent matching changes to dmk2cw?

**Comment by TimothyPMann** [comment]
> Are we going to eventually need to make an equivalent matching changes to dmk2cw?

No, dmk2cw doesn't have a maximum number of tracks.

**Comment by qbarnes** [comment]
I should have expanded my earlier comment.  My comment had to do with the use of `track > 43` in dmk2cw.c:1027 and the comments surrounding it in dmk2cw.man when using the `-h` option.  I didn't know if the change from 43->44 was applicable here or if the 43 use here for some other reason.

**Comment by TimothyPMann** [comment]
> I should have expanded my earlier comment. My comment had to do with the use of `track > 43` in dmk2cw.c:1027 and the comments surrounding it in dmk2cw.man when using the `-h` option. I didn't know if the change from 43->44 was applicable here or if the 43 use here for some other reason.

That 43 is entirely unrelated to cw2dmk's maximum tracks. 77-track 8" drives have a signal on their 50-pin bus called TG43 (track greater than 43). It's used to change the write current used for the higher numbered tracks. The Catweasel lets you control that signal, and dmk2cw has code to set it.

**Pull request merged**
